const moleculesData = [
    { name: "Water", abbr: "H2O", smiles: "O", tags: ["solvent", "polar"] },
    { name: "Phosphate", abbr: "Pi", smiles: "O=P(O)(O)O", tags: ["ion", "acidic"] },
    { name: "Lysine", abbr: "Lys", smiles: "NCCCCC(N)C(=O)O", tags: ["amino-acid", "basic"] },
    { name: "Arginine", abbr: "Arg", smiles: "NC(N)=NCCCC(N)C(=O)O", tags: ["amino-acid", "basic"] },
    { name: "Adenine", abbr: "Ade", smiles: "Nc1ncnc2[nH]cnc12", tags: ["purine", "base"] },
    { name: "Guanine", abbr: "Gua", smiles: "Nc1nc2[nH]cnc2c(=O)[nH]1", tags: ["purine", "base"] },
    { name: "Cytosine", abbr: "Cyt", smiles: "Nc1cc(=O)[nH]cn1", tags: ["pyrimidine", "base"] },
    { name: "Thymine", abbr: "Thy", smiles: "Cc1c[nH]c(=O)[nH]c1=O", tags: ["pyrimidine", "base"] },
    { name: "Uracil", abbr: "Ura", smiles: "O=c1cc[nH]c(=O)[nH]1", tags: ["pyrimidine", "base"] },
    { name: "Pyrophosphate", abbr: "PPi", smiles: "O=P(O)(O)OP(=O)(O)O", tags: ["ion", "energy"] },
    { name: "Ribose", abbr: "Rib", smiles: "OC[C@H]1OC(O)[C@H](O)[C@@H]1O", tags: ["sugar", "carbohydrate"] },
    { name: "Deoxyribose", abbr: "Deoxy", smiles: "OC[C@H]1OC(O)C[C@@H]1O", tags: ["sugar", "carbohydrate"] },
    { name: "Inosine", abbr: "I", smiles: "O=c1[nH]cnc2nc[nH]c12", tags: ["purine", "modified-base"] },
    { name: "Dihydrouridine", abbr: "D", smiles: "O=C1CCNC(=O)N1", tags: ["pyrimidine", "modified-base"] },
    { name: "Lysidine", abbr: "k2C", smiles: "O=C1N(CCCC[C@@H](N)C(=O)O)C(N)=CC1", tags: ["pyrimidine", "modified-base", "amino-acid-conjugate"] },
    { name: "3-methylcytidine", abbr: "m3C", smiles: "CN1C=CC(=O)NC1=N", tags: ["pyrimidine", "modified-base"] },
    { name: "N(2)-dimethylguanosine", abbr: "m22G", smiles: "CN(C)C1=Nc2[nH]cnc2C(=O)N1", tags: ["purine", "modified-base"] },
    { name: "7-methylguanosine", abbr: "m7G", smiles: "C[n+]1cnc2c1nc(N)[nH]c2=O", tags: ["purine", "modified-base"] },
    { name: "Pseudouridine", abbr: "Psi", smiles: "O=c1[nH]cc(C2OC(CO)C(O)C2O)c(=O)[nH]1", tags: ["pyrimidine", "modified-base", "isomer"] },
    { name: "1-methyladenosine", abbr: "m1A", smiles: "CN1C=NC2=C1N=CN=C2N", tags: ["purine", "modified-base"] }
];
